### ISSUE TITLE
Unexpected character encountered while parsing value: <. Path '', line 0, position 0

### ISSUE THREAD

**Issue by grabthefish** [FailedShack/USBHelperLauncher#13]
I followed the instructions from the [reddit post](https://www.reddit.com/r/CemuPiracy/comments/8gj8z8/workaround_download_and_run_wii_u_usb_helper/)

I used the recommended Wii U USB Helper version 0.6.1.616 and version 0.10 of the launcher.
Extracted the helper and then the launcher in a folder.
Downloaded the MakeHostjson.exe to the same folder and ran it.
It created a hosts.json file with the following content:
``` 
{
  "wiiu.titlekeys.gq": "104.129.56.137",
  "3ds.titlekeys.gq": "104.129.56.137"
}
```
I then ran the USBHelperLauncher.exe follow and the steps.
After the screen for entering the key site urls (I only entered the 3DS one)

It then went to the loading screen which then open a messagebox with an error:
![image](https://user-images.githubusercontent.com/12375347/43994241-20487758-9d9a-11e8-89c4-9a5a3a7bea51.png)

Here is the error in text:
```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at A.cb40090777e77bca24d8e80d3881b439d.cce9af53283cfef7a284b260db9a1d817()
   at A.cc84e78656043d401078b58e0ff35dd48.c92d03d65be2d0258da80fddaecea1a40(String cdfa8e5617f0f17ad7922772c65a24101, String cf5ebc69cfa72da3a26dd73059f240e22, String c36a183e2dbd0d173787c2e03a4f16f7b, String c3029528951ef0168af81715363b76fec, String c5e216fee1598eefe98d57d284990be9b, String ca3f713b6e43c226a506a88182c1e9082, Boolean c84f82f13ff05d0c550c815f6d47dc853, Byte[] c1e9648e54295aa0c92cd31a9812e8b5d, Byte[] c7f19abd9146d40d0012f1ece53410cea, c33b9cfba40fb236bddfe6249d60760cf cbdeb41ecef96a7236d7770ceee883278, Action`1 cda887ab9e51268b4e7b21d42329d0e24)
   at A.cb6cc9a5b122137bc5f2718f61ab49e59.cc3ddcea0d3be09242a6a70c83078277f_Encrypted$(cb6cc9a5b122137bc5f2718f61ab49e59 , Byte[] , Byte[] )
```

I had previously adjusted my hosts file using the fix_titlekeys.bat file found in the discord after i learned that the dns records broke of the title keys site

**Comment by klepp0906** [comment]
same error.  oddly enough it worked fine yesterday.

**Comment by klepp0906** [comment]
yea i just deleted the appdata folder and it started working again.  Will be mighty inconvenient if thats required all the time.  We shall see.  Will keep an eye and post back if it persists.

**Comment by FailedShack** [comment]
This is addressed in the troubleshooting section of the Reddit thread.
The solution was to right click the launcher's tray icon and go to Advanced -> Clear Install.
