### ISSUE TITLE
GetRSA() call causes exception

### ISSUE THREAD

**Issue by github-man** [FailedShack/USBHelperLauncher#28]
Hello FailedShack. Below is the output - Windows 10 1803 with latest Nov patches. Running v0.12b

usbhelperlauncher.exe -showconsole
Made by FailedShack
Injected module initializer.

Unhandled Exception: System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.

   at System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters, Boolean useDefaultKeySize)
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters)
   at USBHelperLauncher.Program.GetRSA()
   at USBHelperLauncher.Program.Main(String[] args)

**Comment by github-man** [comment]
the solution for this:
Open C:\Users\%username%\AppData\Roaming\Microsoft\Crypto\RSA then the S-xxxxx sub folder
Open each file withi n this in a text editor looking for the one containing the string "USBhelper" on the first line. Once you have found it, delete it. 

Re-run usbhelperlauncher.exe

**Comment by FailedShack** [comment]
This has been a known issue for some time now and it appears to be a Windows bug.
This is fixed in 5087062193b385ac506986395fa436d9959680b6 by avoiding the usage of a key container.
