### ISSUE TITLE
InvalidOperationException thrown on FIPS-enabled Windows install

### ISSUE THREAD

**Issue by lnguyen7git** [FailedShack/USBHelperLauncher#84]
Can someone help me please? I cannot get this to run it keeps running into error code 0xe0434352. Here is the file it generated:

https://api.nul.sh/logs/fUo9B-AeGIuq

**Comment by FailedShack** [comment]
Original log:

> ------------- USBHelperLauncher Debug Information -------------
Debug Time: 5/11/2022 9:35:38 PM (UTC)
Session Length: 00:00:14
Session GUID: 788fb45f-7014-4ee9-9b78-d157ac97c9ad
Proxy Available: Yes
Public Key Override: Yes
Version: 0.17d
Helper Version: 0.6.1.653
.NET Framework Version: 4.8 or later
Operating System: Microsoft Windows 10 Pro (64-bit)
Platform: Win32NT
Used Locale: en-US
System Language: en-US
Total Memory: 17101807616
Available Memory: 10599088128
Antivirus Software:
Windows Defender -> Enabled
Endpoint Fallbacks:
ContentEndpoint -> https://cdn.shiftinv.cc/wiiuusbhelper/cdn/
-------------------------- Log Start --------------------------
Made by FailedShack
Updated translations: 60312-9699b-5de471861126a
Injected module initializer.
Sending information to injector...
Wii U USB Helper returned non-zero exit code 0xe0434352:
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   at System.Security.Cryptography.MD5.Create()
   at USBHelperInjector.Patches.StringLocalizationPatch.Postfix(String& __result)
   at DMD<DMD<c5dd75c94760bfb37727a44ddc794d278_Patch1>?21433709::c5dd75c94760bfb37727a44ddc794d278_Patch1>(Int32 c6d90c75477d966c1350c18dcdfa11588)
   at WIIU_Downloader.Properties.Settings.get_AppId()
   at DMD<DMD<ce0be635e443d424596522127e6756824_Patch0>?43556055::ce0be635e443d424596522127e6756824_Patch0>(String[] c3c9260886a6db15de49329a9f5b9836c)
---------------------- Fiddler Log Start ----------------------
Fiddler ICertificateProvider v5.0.0.0 loaded.
	fiddler.certmaker.bc.Debug:	False
	ObjectID:			0x2a125d8
Setting upstream gateway to none

Fixed in e73b865c997f4b91db75da2d449e29455a8fd023
